name: 'Harbor Scan Results'
description: 'Get vulnerability scan results from Harbor registry'
author: 'Department of Information Technology'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  registry:
    description: 'Harbor registry domain'
    required: false
  proto:
    description: 'Protocol to use for the Harbor registry'
    required: false
    default: 'https'
  port:
    description: 'Port to use for the Harbor registry'
    required: false
  image:
    description: 'Image to get scan results for'
    required: false
  username:
    description: 'Harbor username'
    required: true
  password:
    description: 'Harbor password'
    required: true
  project-name:
    description: 'Harbor project name'
    required: false
  repository-name:
    description: 'Harbor repository name'
    required: false
  digest:
    description: 'Image digest to scan'
    required: true
  max-attempts:
    description: 'Maximum number of attempts to check scan status'
    required: false
    default: '30'
  sleep-interval:
    description: 'Sleep interval between attempts in seconds'
    required: false
    default: '5'

# Define your outputs here.
outputs:
  scan-results:
    description: 'JSON string containing the scan results'
  report-markdown:
    description: 'Markdown formatted vulnerability report'

runs:
  using: 'node20'
  main: 'dist/index.js'
